### ISSUE TITLE
Possible to support index queries

### ISSUE THREAD

**Issue by peekxc** [thk686/kdtools#1]
@thk686 

using kdtools v0.4.0

Consider the followed supported by the package

```
set.seed(1234)
x <- matrix(runif(200), 100)
y <- kd_sort(x)
kd_range_query(y, c(1/3, 1/3), c(2/3, 2/3))
```

`kd_range_query` currently returns the points within the given bounding region. I would like to be able to do something like: 

```
kd_range_query(y, c(1/3, 1/3), c(2/3, 2/3))
> [1]  2  9 34 41 44 46 48 57 77 82
```

where the result are the original indexes of the points within the bounding region. I figured maybe this would be a trivial thing to implement with `kd_order` + the addition of function similar to the current range query function. Is kdtools able to support this type of query?

**Comment by thk686** [comment]
Probably all functions should support both with a switch. Its quite easy to
implement. I may not get to it quickly however.

**Comment by peekxc** [comment]
@thk686 

Sounds good. Out of curiosity, if I was trying to implement this myself, is there a specific strategy you'd recommend? 

The two approaches I was thinking of was to either: 

A. Come up with an alternative to the `copy_if` template here: 

https://github.com/thk686/kdtools/blob/6f3580f085720d7a05870ea62adaee3ec45d3890/inst/include/kdtools.h#L532-L534

such that the output iterator is given a range over the ordered indices from `kd_order` if the`within` wrapper predicate holds for the numeric range.   

B. Somehow use a custom container+comparator, similar to what was used in the section on [mixed queries](https://thk686.github.io/kdtools/articles/methods.html#mixed-type-searches) to compare only the numeric values of the container. Something like (pseudo-code):

```
void idx_query(IntegerVector idx, List x) // x == arrayvec object 
{
  auto n = x.size();
  range_type data;
  data.reserve(n);
  transform(begin(idx), end(idx), begin(x), back_inserter(data), make_key());  
  kd_sort(begin(data), end(data), <Comparator which ignores first dimension>);
  ...
}
```
Do you think either of those would be close to what you would do?

**Comment by thk686** [comment]
Do you want a solution in C++ or in R? The easy way is to loop over the std::array and call std::distance to get the offsets.

THK

**Comment by thk686** [comment]
I needed this also and so it is now fixed in the latest commit. Try "kd_nn_indices".
