### ISSUE TITLE
kd_is_sorted(kd_sort(data)) returns FALSE

### ISSUE THREAD

**Issue by albertiniufu** [thk686/kdtools#3]
It's first time I use the kdtools, so I'm not sure if I found an issue but couldn't find help anywhere else.

My (very simplified) data (attached in bi.txt) is the following:

> data
      [,1] [,2] [,3]
 [1,]    2    1    0
 [2,]    1    0    0
 [3,]    1    0    0
 [4,]    1    1    0
 [5,]    1    0    0
 [6,]    1    1    0
 [7,]    1    1    0
 [8,]    1    1    0
 [9,]    1    1    0
[10,]    1    0    0
[11,]    1    1    0
[12,]    1    1    0
[13,]    1    0    1
[14,]    1    0    0
[15,]    1    1    0
[16,]    1    1    1

When I try the following I get:

> kd_is_sorted(kd_sort(data))
[1] FALSE

However the following produces a different result:
> kd_is_sorted(kd_sort(data[2:16,]))
[1] TRUE

Is this a real issue?

[bi.txt](https://github.com/thk686/kdtools/files/4899716/bi.txt)

**Comment by thk686** [comment]
Can you provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? At a minimum, I need the output of `sessionInfo()`. You might also look at the [reprex](https://cran.r-project.org/package=reprex) package. Also a few comments [here](http://adv-r.had.co.nz/Reproducibility.html).

**Comment by thk686** [comment]
![image](https://user-images.githubusercontent.com/592841/87234048-d5ede280-c392-11ea-8437-a50ca8f13a54.png)
